import {useEffect,useState,type FormEvent} from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import {CommunityManifest,type CommunityCatalog,type CommunityDetail,type CommunitySkill,type CommunityPackage,type CommunityToken} from '@nest/schemas';
import {apiFetch,apiJson,getApiHeaders} from './api';
import {DesignIcon} from './Dashboard';
import {AgentAvatar} from './components/AgentAvatar';
import type {Agent} from './types';
import './community.css';
const categories=[['','All'],['automation','Automations'],['skill','Agent skills'],['use-case','Use cases']] as const;
const label=(category:string)=>categories.find(([key])=>key===category)?.[1] ?? category;
function errorMessage(error:unknown){const value=error instanceof Error?error.message:'Unable to load community';try{return JSON.parse(value).error ?? value;}catch{return value;}}
const instructions=(markdown:string)=>markdown.replace(/^---\r?\n[\s\S]*?\r?\n---\r?\n/,'');
function packageFrom(detail:CommunityDetail):CommunityPackage{const {author,ownerId,digest,createdAt,updatedAt,versionCount,fileCount,canPublish,...manifest}=detail.skill;return {schemaVersion:1,manifest,files:detail.files.map(({bytes,sha256,...file})=>file)};}
export function Community({skillName,onSelect,onMenu,agents}:{skillName:string|null;onSelect:(name:string|null)=>void;onMenu:()=>void;agents:Agent[]}){
  const [catalog,setCatalog]=useState<CommunityCatalog|null>(null);
  const [detail,setDetail]=useState<CommunityDetail|null>(null);
  const [error,setError]=useState<string|null>(null);
  const [detailError,setDetailError]=useState<string|null>(null);
  const [busy,setBusy]=useState(true);
  const [refresh,setRefresh]=useState(0);
  const [query,setQuery]=useState('');const [category,setCategory]=useState('');const [offset,setOffset]=useState(0);
  const [publishing,setPublishing]=useState(false);const [installing,setInstalling]=useState(false);const [showTokens,setShowTokens]=useState(false);const [version,setVersion]=useState('');
  useEffect(()=>{const controller=new AbortController();setBusy(true);setError(null);
    const timeout=window.setTimeout(()=>void apiJson<CommunityCatalog>(`/api/community/skills?${new URLSearchParams({q:query,category,offset:String(offset)})}`,{signal:controller.signal}).then(value=>{if(!controller.signal.aborted)setCatalog(value);}).catch(reason=>{if(!controller.signal.aborted)setError(errorMessage(reason));}).finally(()=>{if(!controller.signal.aborted)setBusy(false);}),150);
    return()=>{controller.abort();window.clearTimeout(timeout);};
  },[refresh,query,category,offset]);
  useEffect(()=>{setVersion('');setPublishing(false);setInstalling(false);},[skillName]);
  useEffect(()=>{setDetail(null);setDetailError(null);if(!skillName)return;
    const controller=new AbortController();
    apiJson<CommunityDetail>(`/api/community/skills/${encodeURIComponent(skillName)}${version?`?version=${encodeURIComponent(version)}`:''}`,{signal:controller.signal}).then(value=>{if(!controller.signal.aborted)setDetail(value);}).catch(reason=>{if(!controller.signal.aborted)setDetailError(errorMessage(reason));});return()=>controller.abort();
  },[skillName,version,refresh]);
  const skills=catalog?.skills ?? [];
  const authors=new Map<string,{name:string;kind:string;count:number}>();
  for(const skill of skills){const key=`${skill.author.kind}:${skill.author.name}`;const author=authors.get(key)??{...skill.author,count:0};author.count++;authors.set(key,author);}
  function card(skill:CommunitySkill){return <article className="dashboard-card community-card" key={skill.name}>
    <div className="community-card-banner"><img src={`${import.meta.env.BASE_URL}design/community-cover.png`} alt="" aria-hidden="true"/></div>
    <div className="community-card-body"><div className="community-byline"><span aria-hidden="true">{skill.author.kind==='agent'?<AgentAvatar name={skill.author.name} size={36}/>:<span className="community-initials">{skill.author.name.slice(0,2)}</span>}</span><span><strong>{skill.author.name}</strong><small>{skill.author.kind==='agent'?'Agent':'Person'} · {new Date(skill.updatedAt).toLocaleDateString()}</small></span><span className="dashboard-pill">{label(skill.category)}</span></div>
    <h2><button onClick={()=>onSelect(skill.name)}>{skill.title}</button></h2><p>{skill.description}</p><div className="community-tags">{skill.tags.map(tag=><button key={tag} onClick={()=>{setQuery(tag);setOffset(0);}}>#{tag}</button>)}</div>
    <footer><span>{skill.versionCount} {skill.versionCount===1?'version':'versions'} · {skill.fileCount} {skill.fileCount===1?'file':'files'}</span><button className="dashboard-action community-primary" onClick={()=>onSelect(skill.name)}>View skill →</button></footer></div>
  </article>;}
  const saved=(name:string)=>{setPublishing(false);setVersion('');setRefresh(n=>n+1);onSelect(name);};
  return <section className="dashboard community-page" aria-label="Community"><header className="dashboard-topbar"><button className="sidebar-mobile-toggle" onClick={onMenu}>Menu</button><label className="dashboard-search"><DesignIcon name="search"/><input aria-label="Search community" placeholder="Search community…" value={query} onChange={event=>{setQuery(event.target.value);setOffset(0);if(skillName)onSelect(null);}}/></label><span className="community-tenant-label">Private tenant community</span></header>
    <div className="dashboard-content"><div className="dashboard-title"><h1>{detail?.skill.title ?? 'Community'}</h1>{skillName?<button className="dashboard-action" onClick={()=>onSelect(null)}>All skills</button>:<button className="dashboard-action community-publish-button" onClick={()=>setPublishing(!publishing)}>{publishing?'Close editor':'Share a skill +'}</button>}</div>
    {error&&<p className="notice error" role="alert">{error} <button onClick={()=>setRefresh(n=>n+1)}>Retry</button></p>}
    {busy&&<p role="status">Loading community…</p>}
    {publishing&&<PublishSkill key={detail?.skill.name??'new'} initial={skillName&&detail?packageFrom(detail):undefined} onSaved={saved}/>}
    {showTokens&&<AgentAccess agents={agents}/>}
    <div className="community-layout"><div className="community-feed">
    {skillName?<>
      {detailError&&<p className="notice error" role="alert">{detailError} <button onClick={()=>setRefresh(n=>n+1)}>Retry</button></p>}
      {!detail&&!detailError&&<p role="status">Loading skill…</p>}
      {detail&&<article className="dashboard-card community-detail"><div className="community-byline"><span className="dashboard-pill">{label(detail.skill.category)}</span><span>v{detail.skill.version} · {detail.skill.license}</span></div><p>{detail.skill.description}</p><p>Published by {detail.skill.author.name} · {detail.skill.author.kind==='agent'?'Agent':'Person'}</p>
      <label className="community-version">Version<select aria-label="Skill version" value={detail.skill.version} onChange={event=>{setPublishing(false);setVersion(event.target.value);}}>{detail.versions.map(release=><option key={release.version} value={release.version}>{release.version}</option>)}</select></label>
      <div className="community-detail-actions"><button className="dashboard-action community-primary" onClick={()=>setInstalling(!installing)}>{installing?'Hide install instructions':'Install skill'}</button><a href={`/api/community/skills/${detail.skill.name}/download?version=${detail.skill.version}`} download>Download package ↓</a>{detail.skill.canPublish&&<button className="dashboard-action" onClick={()=>setPublishing(!publishing)}>Publish new version</button>}</div>
      {installing&&<InstallSkill detail={detail}/>}
      <h2>Instructions</h2><div className="project-markdown community-markdown"><ReactMarkdown remarkPlugins={[remarkGfm]} skipHtml components={{img:({alt})=><span>{alt ?? 'Image in package'}</span>}}>{instructions(detail.files.find(file=>file.path==='SKILL.md')!.content)}</ReactMarkdown></div>
      <h2>Package files</h2><ul className="community-files">{detail.files.map(file=><li key={file.path}><span>{file.path}{file.executable?' · executable':''}</span><span>{file.bytes.toLocaleString()} bytes</span></li>)}</ul><p className="community-muted">SHA-256: <code>{detail.skill.digest}</code>. Published versions are immutable. Publishing stores files; it does not execute them.</p></article>}
    </>:<><button className="dashboard-card community-compose" onClick={()=>setPublishing(true)}><span className="community-compose-icon">+</span><span>Share an automation, skill or use case…<small>Visible only to people and authorized agents in this tenant.</small></span></button><nav className="community-filters" aria-label="Community categories">{categories.map(([value,title])=><button key={value} aria-pressed={category===value} onClick={()=>{setCategory(value);setOffset(0);}}>{title}</button>)}</nav>
    {skills.map(card)}{!busy&&!error&&!skills.length&&<div className="dashboard-card dashboard-empty"><h2>{query||category?'No matching skills':'Build your shared skill library'}</h2><p>{query?'Try a different name or tag.':'Publish a skill your team can reuse. People and agents share the same versioned catalog.'}</p><button onClick={()=>setPublishing(true)}>Share your first skill →</button></div>}
    {catalog&&catalog.total>catalog.limit&&<div className="community-pagination"><button className="dashboard-action" disabled={!offset||busy} onClick={()=>setOffset(Math.max(0,offset-catalog.limit))}>Previous</button><span>{offset+1}–{Math.min(offset+catalog.limit,catalog.total)} of {catalog.total}</span><button className="dashboard-action" disabled={offset+catalog.limit>=catalog.total||busy} onClick={()=>setOffset(offset+catalog.limit)}>Next</button></div>}</>}
    </div><aside className="community-aside"><section><h2>Recently published</h2>{skills.slice(0,5).map(skill=><button className="dashboard-card community-compact" key={skill.name} onClick={()=>onSelect(skill.name)}><span className="community-initials">{skill.category==='automation'?'↻':'✧'}</span><span><strong>{skill.title}</strong><small>{label(skill.category)} · v{skill.version}</small></span></button>)}{!skills.length&&<p>Your team’s skills will appear here.</p>}</section><section><h2>Contributors</h2>{[...authors.values()].sort((a,b)=>b.count-a.count).map(author=><div className="community-contributor" key={`${author.kind}:${author.name}`}><span>{author.name}<small>{author.kind==='agent'?'Agent':'Person'}</small></span><small>{author.count} {author.count===1?'skill':'skills'}</small></div>)}<p className="community-muted">Contributions in the current results.</p></section><section><h2>Agents can contribute</h2><p>Give an agent a revocable token for this catalog. Its publications are attributed to its existing Nest identity.</p><button className="dashboard-action" onClick={()=>setShowTokens(!showTokens)}>{showTokens?'Close agent access':'Manage agent access'}</button></section></aside></div></div></section>;
}
function InstallSkill({detail}:{detail:CommunityDetail}){
  const [runtime,setRuntime]=useState('codex');const [copied,setCopied]=useState('');
  const destination=runtime==='orgops'?'/app/.nest-data/engine/skills':'"$HOME/.agents/skills"';
  const command=`node scripts/community.mjs install ./Downloads/${detail.skill.name}-${detail.skill.version}.nest-skill.json --dest ${destination}`;
  return <section className="community-install" aria-label="Install instructions"><h2>Install a reviewed copy</h2><label>Target runtime<select value={runtime} onChange={event=>setRuntime(event.target.value)}><option value="codex">Codex / compatible local runtime</option><option value="orgops">Nest native agent (OrgOps)</option></select></label><p>Download the package, review its instructions and supporting files, then run this from a Nest checkout on the agent’s host. Replace the package path with the actual download location.</p><pre><code>{command}</code></pre><button className="dashboard-action" onClick={()=>void navigator.clipboard.writeText(command).then(()=>setCopied('Copied')).catch(()=>setCopied('Select and copy the commands above.'))}>Copy command</button><p role="status">{copied}</p><p>{runtime==='orgops'?'Use the skills directory on the assigned runner, then enable the skill in the agent’s settings. The example path is for Nest’s single-container deployment.':'Use your external runtime’s configured skills directory if it differs from the example.'} Existing installs are not overwritten. Installation does not start an agent or schedule an automation.</p></section>;
}
function PublishSkill({initial,onSaved}:{initial?:CommunityPackage;onSaved:(name:string)=>void}){
  const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  const initialVersion=initial?.manifest.version.split('.')??['1','0','0'];if(initial)initialVersion[2]=String(BigInt(initialVersion[2])+1n);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setError('');const form=new FormData(event.currentTarget);
    const result=CommunityManifest.safeParse({name:form.get('name'),title:form.get('title'),description:form.get('description'),version:form.get('version'),category:form.get('category'),license:form.get('license'),tags:String(form.get('tags')).split(',').map(s=>s.trim()).filter(Boolean),runtimes:String(form.get('runtime')).split(',')});
    const text=String(form.get('instructions') ?? '').trim();
    if(!result.success){setError(result.error.issues.map(issue=>`${issue.path.join('.')}: ${issue.message}`).join('; '));return;}
    if(text.length<40||text.length>60000){setError('Write between 40 and 60,000 characters of useful instructions.');return;}
    const manifest=result.data;const content=`---\nname: ${manifest.name}\ndescription: ${JSON.stringify(manifest.description)}\nlicense: ${manifest.license}\n---\n\n${text}\n`;
    setBusy(true);
    try{await apiJson('/api/community/skills',{method:'POST',headers:getApiHeaders(),body:JSON.stringify({schemaVersion:1,manifest,files:[{path:'SKILL.md',content,encoding:'utf8',executable:false},...(initial?.files.filter(f=>f.path!=='SKILL.md')??[])]})});onSaved(manifest.name);}
    catch(reason){setError(errorMessage(reason));}finally{setBusy(false);}
  }
  return <form className="dashboard-card community-editor" onSubmit={event=>void submit(event)}><h2>{initial?'Publish a new version':'Share a reusable skill'}</h2><p>Publish to this tenant’s private catalog. People and authorized agents here can discover and download it. Published versions cannot be overwritten.</p>{error&&<p role="alert">{error}</p>}<fieldset disabled={busy}><div className="community-form-grid"><label>Skill name<input name="name" required maxLength={63} defaultValue={initial?.manifest.name} readOnly={Boolean(initial)} placeholder="weekly-product-pulse" pattern="[a-z0-9]+(-[a-z0-9]+)*"/></label><label>Display title<input name="title" required maxLength={100} defaultValue={initial?.manifest.title}/></label><label className="community-full">Description<textarea name="description" required minLength={10} maxLength={500} rows={2} defaultValue={initial?.manifest.description}/></label><label>Version<input name="version" required defaultValue={initialVersion.join('.')}/></label><label>Category<select name="category" defaultValue={initial?.manifest.category??'skill'}><option value="skill">Agent skill</option><option value="automation">Automation</option><option value="use-case">Use case</option></select></label><label>License<select name="license" defaultValue={initial?.manifest.license??'Proprietary'}><option>Proprietary</option><option>MIT</option><option>Apache-2.0</option><option>CC-BY-4.0</option></select></label><label>Runtime<select name="runtime" defaultValue={initial?.manifest.runtimes.join(',')??'generic'}>{initial&&<option value={initial.manifest.runtimes.join(',')}>{initial.manifest.runtimes.join(', ')}</option>}<option value="generic">Runtime independent</option><option value="codex">Codex / compatible runtime</option><option value="orgops">OrgOps native</option></select></label><label className="community-full">Tags (comma separated)<input name="tags" placeholder="product, feedback" defaultValue={initial?.manifest.tags.join(', ')}/></label><label className="community-full">Instructions<textarea name="instructions" required minLength={40} maxLength={60000} rows={8} defaultValue={initial?instructions(initial.files.find(f=>f.path==='SKILL.md')?.content??''):''} placeholder="When to use this skill, required inputs, steps, expected output and external actions…"/></label></div><p>Keep credentials outside the package. Supporting scripts and assets can be published with the agent CLI/API; this editor preserves them on version updates.</p><button className="dashboard-action community-primary">{busy?'Publishing…':initial?'Publish version':'Publish skill'}</button></fieldset></form>;
}
function AgentAccess({agents}:{agents:Agent[]}){
  const [tokens,setTokens]=useState<CommunityToken[]>([]);const [secret,setSecret]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [refresh,setRefresh]=useState(0);
  useEffect(()=>{const controller=new AbortController();void apiJson<CommunityToken[]>('/api/community/tokens',{signal:controller.signal}).then(setTokens).catch(reason=>{if(!controller.signal.aborted)setError(errorMessage(reason));});return()=>controller.abort();},[refresh]);
  async function issue(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);setBusy(true);setError('');setSecret('');try{const result=await apiJson<{token:string}>('/api/community/tokens',{method:'POST',headers:getApiHeaders(),body:JSON.stringify({agentName:form.get('agent')})});setSecret(result.token);setRefresh(n=>n+1);}catch(reason){setError(errorMessage(reason));}finally{setBusy(false);}}
  async function revoke(id:string){setError('');try{await apiFetch(`/api/community/tokens/${id}`,{method:'DELETE'});setSecret('');setRefresh(n=>n+1);}catch(reason){setError(errorMessage(reason));}}
  return <section className="dashboard-card community-editor" aria-label="Agent community access"><h2>Agent publishing access</h2><p>Tokens expire after 30 days. They allow reading this catalog and publishing that agent’s skills, with no access to chat, deployment or other Nest APIs. Only an agent’s owner or the instance owner can issue one.</p>{error&&<p role="alert">{error}</p>}<form onSubmit={event=>void issue(event)}><label>Publishing agent<select name="agent" required defaultValue=""><option value="" disabled>Choose an agent</option>{agents.map(agent=><option key={agent.name}>{agent.name}</option>)}</select></label><button className="dashboard-action" disabled={busy}>{busy?'Creating…':'Create publishing token'}</button></form>{secret&&<div className="community-install"><label>New token (shown once)<input aria-label="New community token" type="password" readOnly value={secret}/></label><button className="dashboard-action" onClick={()=>void navigator.clipboard.writeText(secret).catch(()=>setError('Select and copy the token field.'))}>Copy token</button><p>Store this in the agent’s secret environment as NEST_COMMUNITY_TOKEN, not in its skill files or chat.</p></div>}<pre className="community-agent-command">NEST_COMMUNITY_URL={window.location.origin}{`\n`}node scripts/community.mjs search review{`\n`}node scripts/community.mjs publish ./my-skill.nest-skill.json</pre><p>Set NEST_COMMUNITY_URL and NEST_COMMUNITY_TOKEN in the agent process environment. The CLI reads both without printing the token.</p><ul className="community-token-list">{tokens.map(token=><li key={token.id}><span>{token.agentName} · {token.revokedAt?'Revoked':token.expiresAt<Date.now()?'Expired':`Expires ${new Date(token.expiresAt).toLocaleDateString()}`}</span>{!token.revokedAt&&<button className="dashboard-action" onClick={()=>void revoke(token.id)}>Revoke</button>}</li>)}</ul></section>;
}
