import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { once } from 'node:events';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createRequire } from 'node:module';
import { createApp as createEngine } from '../../vendor/orgops/apps/api/src/app';
import { createOrgOpsClient } from '../../packages/orgops-client/src/index';
import { createApp } from '../../apps/api/src/app';

const dir=mkdtempSync(join(tmpdir(),'nest-community-browser-'));
const screenshots=mkdtempSync(join(tmpdir(),'nest-community-screenshots-'));
const previousRoot=process.env.ORGOPS_PROJECT_ROOT;process.env.ORGOPS_PROJECT_ROOT=dir;
const engine=createEngine({dbPath:join(dir,'engine.sqlite'),dataDir:dir,adminUser:'owner',adminPass:'test-password',runnerToken:'test-runner'});
if(previousRoot===undefined)delete process.env.ORGOPS_PROJECT_ROOT;else process.env.ORGOPS_PROJECT_ROOT=previousRoot;
const orgops=createOrgOpsClient('http://engine',(async(url,init)=>engine.app.fetch(new Request(url,init))) as typeof fetch);
const product=createApp({orgops,dbPath:join(dir,'product.sqlite')});
const uiRequire=createRequire(join(process.cwd(),'apps/user-ui/package.json'));
const apiRequire=createRequire(join(process.cwd(),'apps/api/package.json'));
const {serve}=apiRequire('@hono/node-server');
const backend=serve({fetch:product.app.fetch,hostname:'127.0.0.1',port:0});
await once(backend,'listening');
const backendUrl=`http://127.0.0.1:${backend.address().port}`;
const {createServer}=await import(uiRequire.resolve('vite'));
const server=await createServer({root:join(process.cwd(),'apps/user-ui'),server:{host:'127.0.0.1',port:5299,strictPort:true,proxy:{'/api':backendUrl}}});
try {
  await server.listen();
  const browser=await chromium.launch({headless:true});
  try {
    const page=await browser.newPage({viewport:{width:1440,height:1100}});page.setDefaultTimeout(15000);
    const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
    const login=await product.app.request('/api/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username:'owner',password:'test-password'})});
    assert.equal(login.status,200);
    const cookie=login.headers.get('set-cookie')!.split(';')[0];
    const headers={cookie,'content-type':'application/json'};
    const created=await product.app.request('/api/agents',{method:'POST',headers,body:JSON.stringify({name:'Builder',modelId:'test-model',workspacePath:join(dir,'workspace')})});assert.equal(created.status,201);
    await page.context().addCookies([{name:'nest_session',value:cookie.slice('nest_session='.length),url:'http://127.0.0.1:5299',httpOnly:true}]);
    await page.routeWebSocket('**/ws',socket=>socket.close());
    await page.goto('http://127.0.0.1:5299/');await page.getByRole('heading',{name:'Dashboard',exact:true}).waitFor();
    const nav=page.getByRole('navigation',{name:'Main navigation'});
    await nav.getByRole('button',{name:'Community',exact:true}).click();
    await page.getByRole('heading',{name:'Build your shared skill library'}).waitFor();
    assert.equal(new URL(page.url()).searchParams.get('view'),'community');
    assert.equal(await nav.getByRole('button',{name:'Community',exact:true}).getAttribute('aria-current'),'page');
    await page.getByRole('button',{name:'Share a skill +',exact:true}).click();
    await page.getByRole('textbox',{name:'Skill name',exact:true}).fill('acceptance-review');
    await page.getByRole('textbox',{name:'Display title',exact:true}).fill('Acceptance Review');
    await page.getByRole('textbox',{name:'Description',exact:true}).fill('Review the deliverable against clear acceptance criteria.');
    await page.getByRole('textbox',{name:'Tags (comma separated)',exact:true}).fill('review, quality');
    await page.getByRole('textbox',{name:'Instructions',exact:true}).fill('# Acceptance Review\nRead the supplied criteria and provide evidence for every conclusion. Distinguish unmet criteria from unverified requirements.');
    await page.getByRole('button',{name:'Publish skill',exact:true}).click();
    await page.getByRole('heading',{name:'Acceptance Review',exact:true,level:1}).first().waitFor();
    await page.getByRole('button',{name:'Install skill',exact:true}).waitFor();
    assert.equal(new URL(page.url()).searchParams.get('skill'),'acceptance-review');
    const deepLink=page.url();
    await page.getByRole('button',{name:'Publish new version',exact:true}).click();
    assert.equal(await page.getByRole('textbox',{name:'Version',exact:true}).inputValue(),'1.0.1');
    await page.getByRole('textbox',{name:'Instructions',exact:true}).fill('# Acceptance Review\nRead the supplied criteria and provide evidence for every conclusion. Include links to tests that actually ran.');
    await page.getByRole('button',{name:'Publish version',exact:true}).click();
    await page.waitForFunction(()=>document.querySelector('select[aria-label="Skill version"]')?.value==='1.0.1');
    await page.getByRole('combobox',{name:'Skill version',exact:true}).selectOption('1.0.0');
    await page.getByText('Read the supplied criteria and provide evidence for every conclusion. Distinguish unmet criteria from unverified requirements.',{exact:true}).waitFor();
    await page.getByRole('button',{name:'Install skill',exact:true}).click();
    await page.getByRole('region',{name:'Install instructions'}).waitFor();
    const downloadEvent=page.waitForEvent('download');
    await page.getByRole('link',{name:'Download package ↓',exact:true}).click();
    const download=await downloadEvent;const path=join(dir,download.suggestedFilename());await download.saveAs(path);
    const {readFileSync}=await import('node:fs');const {verifyPackage,install}=await import('../../scripts/community.mjs');
    const bundle=JSON.parse(readFileSync(path,'utf8'));assert.equal(verifyPackage(bundle).manifest.version,'1.0.0');
    const installed=install(bundle,join(dir,'installed'));assert(readFileSync(join(installed.path,'SKILL.md'),'utf8').includes('unverified requirements'));
    await page.reload();await page.getByRole('button',{name:'Install skill',exact:true}).waitFor();
    await page.getByRole('button',{name:'All skills',exact:true}).click();
    await page.getByRole('button',{name:'View skill →',exact:true}).waitFor();
    await page.getByRole('button',{name:'Manage agent access',exact:true}).click();
    const access=page.getByRole('region',{name:'Agent community access'});
    await access.getByRole('combobox',{name:'Publishing agent',exact:true}).selectOption('Builder');
    await access.getByRole('button',{name:'Create publishing token',exact:true}).click();
    await page.getByLabel('New community token').waitFor();const token=await page.getByLabel('New community token').inputValue();
    const manifest={name:'weekly-product-pulse',title:'Weekly Product Pulse',description:'Collect product feedback, summarize themes and prepare a weekly update.',version:'1.0.0',category:'automation',license:'Proprietary',tags:['product','feedback'],runtimes:['generic']};
    const body={schemaVersion:1,manifest,files:[{path:'SKILL.md',content:`---\nname: ${manifest.name}\ndescription: ${manifest.description}\nlicense: Proprietary\n---\n\nRead supplied feedback and return a draft weekly summary with evidence and clear next actions. Publishing does not create a schedule.\n`}]};
    const agentHeaders={'content-type':'application/json',authorization:`Bearer ${token}`};
    const publish=await product.app.request('/api/community/skills',{method:'POST',headers:agentHeaders,body:JSON.stringify(body)});assert.equal(publish.status,201);
    await access.getByRole('button',{name:'Revoke',exact:true}).click();await access.getByText('Builder · Revoked',{exact:true}).waitFor();
    assert.equal((await product.app.request('/api/community/skills',{headers:agentHeaders})).status,401);
    await page.reload();await page.getByRole('heading',{name:'Community',exact:true}).waitFor();
    await page.getByRole('button',{name:'Weekly Product Pulse',exact:true}).waitFor();
    await page.waitForFunction(()=>Array.from(document.querySelectorAll('.community-card-banner img,.product-nav img')).every((image:any)=>image.complete&&image.naturalWidth>0));
    await page.screenshot({path:join(screenshots,'community-desktop.png'),fullPage:true});
    await page.getByRole('button',{name:'Automations',exact:true}).click();
    await page.waitForFunction(()=>document.querySelectorAll('.community-card').length===1);
    await page.getByRole('button',{name:'Agent skills',exact:true}).click();
    await page.getByRole('button',{name:'Acceptance Review',exact:true}).waitFor();
    await page.getByRole('textbox',{name:'Search community',exact:true}).fill('missing-skill');
    await page.getByRole('heading',{name:'No matching skills'}).waitFor();
    await page.getByRole('textbox',{name:'Search community',exact:true}).fill('');
    await page.getByRole('button',{name:'All',exact:true}).click();
    await page.getByRole('button',{name:'Acceptance Review',exact:true}).click();
    await page.getByRole('button',{name:'Install skill',exact:true}).waitFor();
    await page.goBack();await page.getByRole('button',{name:'Share a skill +',exact:true}).waitFor();
    await page.goForward();await page.getByRole('button',{name:'Install skill',exact:true}).waitFor();
    await page.goto(deepLink);await page.getByRole('button',{name:'Install skill',exact:true}).waitFor();
    await nav.getByRole('button',{name:'Dashboard',exact:true}).click();assert.equal(new URL(page.url()).searchParams.get('skill'),null);
    await nav.getByRole('button',{name:'Community',exact:true}).click();
    await page.getByRole('button',{name:'Weekly Product Pulse',exact:true}).waitFor();
    await page.setViewportSize({width:390,height:844});
    assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
    await page.screenshot({path:join(screenshots,'community-mobile.png'),fullPage:true});
    await page.getByRole('button',{name:'Menu',exact:true}).click();assert.equal(await nav.getByRole('button',{name:'Community',exact:true}).getAttribute('aria-current'),'page');
    assert.deepEqual(errors,[]);
    console.log(`PASS: private community publication, immutable versions, verified download/install, agent token issue/revoke, search/categories, navigation/history, original Figma assets and mobile. Screenshots: ${screenshots}`);
  } finally {await browser.close();}
} finally {await server.close();await new Promise<void>(resolve=>backend.close(()=>resolve()));product.store.close();engine.db.close();rmSync(dir,{recursive:true,force:true});}
