import {test,expect} from 'vitest';
import {mkdtempSync,mkdirSync,writeFileSync,readFileSync,rmSync,existsSync,symlinkSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {pack,install,verifyPackage} from './community.mjs';
const manifest={name:'review-result',title:'Review Result',description:'Review evidence against acceptance criteria.',version:'1.0.0',category:'skill',license:'Proprietary',tags:['review'],runtimes:['generic']};
function fixture(fn){const dir=mkdtempSync(join(tmpdir(),'nest-community-cli-'));try{const source=join(dir,'source');mkdirSync(source);writeFileSync(join(source,'skill.json'),JSON.stringify(manifest));writeFileSync(join(source,'SKILL.md'),`---\nname: review-result\ndescription: ${manifest.description}\nlicense: Proprietary\n---\n\nCheck the provided evidence against each criterion.\n`);fn(dir,source);}finally{rmSync(dir,{recursive:true,force:true});}}
test('packs and installs resources without execution, preserving bytes and modes',()=>fixture((dir,source)=>{mkdirSync(join(source,'scripts'));const sentinel=join(dir,'executed');writeFileSync(join(source,'scripts/check.sh'),`#!/bin/sh\ntouch '${sentinel}'\n`,{mode:0o755});mkdirSync(join(source,'assets'));writeFileSync(join(source,'assets/binary.bin'),Buffer.from([255,0,128]));const value=pack(source);expect(verifyPackage(value).digest).toBe(value.digest);const result=install(value,join(dir,'installed'));expect(readFileSync(join(result.path,'assets/binary.bin'))).toEqual(Buffer.from([255,0,128]));expect(existsSync(sentinel)).toBe(false);expect(()=>install(value,join(dir,'installed'))).toThrow(/already installed/);}));
test('rejects package and manifest tampering before creating a destination',()=>fixture((dir,source)=>{const value=pack(source);value.files[0].content+='Changed';expect(()=>install(value,join(dir,'installed'))).toThrow(/integrity/);expect(existsSync(join(dir,'installed'))).toBe(false);const changed=pack(source);changed.manifest.name='other';expect(()=>verifyPackage(changed)).toThrow(/integrity/);}));
test('rejects unsafe paths, symlinks and overlapping case-insensitive paths',()=>fixture((dir,source)=>{const value=pack(source);value.files[0].path='../escape';expect(()=>verifyPackage(value)).toThrow(/Unsafe/);symlinkSync('/etc/passwd',join(source,'SKILL-link.md'));expect(()=>pack(source)).toThrow(/Symlinks/);}));
